
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ChiTietGioHang
{

    public string MaChiTietGioHang { get; set; }

    public string MaGioHang { get; set; }

    public Nullable<int> ThanhTien { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public string MaSanPham { get; set; }



    public virtual GioHang GioHang { get; set; }

    public virtual SanPham SanPham { get; set; }

}

}
