
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DonHang
{

    public int id { get; set; }

    public string product_id { get; set; }

    public string customer_id { get; set; }

    public Nullable<System.DateTime> date { get; set; }

    public string status { get; set; }

    public double total_money { get; set; }

    public string voucher { get; set; }



    public virtual SanPham SanPham { get; set; }

    public virtual TrangThaiDonHang TrangThaiDonHang { get; set; }

}

}
