
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class KhuyenMai
{

    public string Makhuyenmai { get; set; }

    public string Maloai { get; set; }

    public Nullable<int> Mucgiam { get; set; }

    public string MaApDung { get; set; }

    public Nullable<int> GTapdung { get; set; }

    public Nullable<System.DateTime> TGbatdau { get; set; }

    public Nullable<System.DateTime> TGketthuc { get; set; }



    public virtual LoaiApDung LoaiApDung { get; set; }

    public virtual LoaiKhuyenMai LoaiKhuyenMai { get; set; }

}

}
