
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SanPham
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanPham()
    {

        this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();

        this.DonHangs = new HashSet<DonHang>();

    }


    public string MaSP { get; set; }

    public string TenSP { get; set; }

    public string ThuongHieu { get; set; }

    public string MaNhom { get; set; }

    public string MoTa { get; set; }

    public int GiaSP { get; set; }

    public int SoLuong { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }

    public virtual NhomSanPham NhomSanPham { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DonHang> DonHangs { get; set; }

}

}
